タイトルなど
dice-2004/Union-Hack-2024 pull request #5
Opened 2024-08-28 16:34 UTC by dice-2004

タイトル画面（仮）
データセーブとデータロードのメソッドの追加
タイトルからゲーム画面に遷移するためのmain関数の変更

をしました

2024-08-28 16:34 UTC, dice-2004 commented
これでよさそうだったらマージしといてください

2024-08-28 16:39 UTC, dice-2004 commented
画面の配置についてはまた後日

2024-08-29 02:32 UTC, d1b26 reviewed
assetディレクトリをsrcの中に入れることは何のためか教えていただきたいです。

2024-08-29 03:06 UTC, d1b26 commented
それ以外は良いと思います。
夜遅くまでの作業お疲れ様でした。

2024-08-29 03:29 UTC, d1b26 commented
こちらの環境だと文字化けしますがそちらの環境ではどうですか?

2024-08-29 06:26 UTC, d1b26 requested changes
申し訳ないがsrc下への移動を修正してほしい

2024-08-29 07:26 UTC, hinshiba approved these changes
修正済み

2024-08-29 07:26 UTC, merged